// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5EiVhHosKqLxp7FWhcdcR5NlEkEwUYgo',
    appId: '1:47576396604:web:b323df88149c08f306e439',
    messagingSenderId: '47576396604',
    projectId: 'forum-2f5bd',
    authDomain: 'forum-2f5bd.firebaseapp.com',
    storageBucket: 'forum-2f5bd.firebasestorage.app',
    measurementId: 'G-QZHLPTS2WG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlCJlTPb-7okd3GNbQV1uOytbEhcMBpRk',
    appId: '1:47576396604:android:a3cfa4b8a4172c5c06e439',
    messagingSenderId: '47576396604',
    projectId: 'forum-2f5bd',
    storageBucket: 'forum-2f5bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB6HzxF7yqbKexeXtDP9tBuSW4zemsHrQ',
    appId: '1:47576396604:ios:9dcb57e3061ac6ff06e439',
    messagingSenderId: '47576396604',
    projectId: 'forum-2f5bd',
    storageBucket: 'forum-2f5bd.firebasestorage.app',
    iosBundleId: 'com.example.forum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB6HzxF7yqbKexeXtDP9tBuSW4zemsHrQ',
    appId: '1:47576396604:ios:9dcb57e3061ac6ff06e439',
    messagingSenderId: '47576396604',
    projectId: 'forum-2f5bd',
    storageBucket: 'forum-2f5bd.firebasestorage.app',
    iosBundleId: 'com.example.forum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5EiVhHosKqLxp7FWhcdcR5NlEkEwUYgo',
    appId: '1:47576396604:web:f235c16a8ef4fcb006e439',
    messagingSenderId: '47576396604',
    projectId: 'forum-2f5bd',
    authDomain: 'forum-2f5bd.firebaseapp.com',
    storageBucket: 'forum-2f5bd.firebasestorage.app',
    measurementId: 'G-J5YMEVDZEW',
  );
}
